[workspace]

members = [
  "crates/hc-utils",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[patch.crates-io]
hdk = {git = "https://github.com/holochain/holochain.git", rev = "a1ae76ecc1fc7dbd645fee3a8cb0df9f610be983", package = "hdk"}
holo_hash = {git = "https://github.com/holochain/holochain.git", rev = "a1ae76ecc1fc7dbd645fee3a8cb0df9f610be983", package = "holo_hash"}
# paste = "1.0.5"
