[workspace]

members = [
  "crates/hc-utils",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[patch.crates-io]
hdk = {git = "https://github.com/holochain/holochain.git", rev = "a8523568753bf7921f5cd90fd40e38402a6471b4", package = "hdk"}
holo_hash = {git = "https://github.com/holochain/holochain.git", rev = "a8523568753bf7921f5cd90fd40e38402a6471b4", package = "holo_hash"}
