[workspace]

members = [
  "crates/hc-utils",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[patch.crates-io]
hdk = {git = "https://github.com/holochain/holochain.git", rev = "bd89d55e397baf7876099f600db997c89dd70fb6", package = "hdk"}
holo_hash = {git = "https://github.com/holochain/holochain.git", rev = "bd89d55e397baf7876099f600db997c89dd70fb6", package = "holo_hash"}
