[workspace]

members = [
  "crates/hc-utils",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[patch.crates-io]
hdk = {git = "https://github.com/holochain/holochain.git", rev = "8c85ba9629631a17b59b77b9a5a0d5f24c700d11", package = "hdk"}
#holo_hash = {git = "https://github.com/holochain/holochain.git", rev = "8c85ba9629631a17b59b77b9a5a0d5f24c700d11", package = "holo_hash"}
# paste = "1.0.5"
