[workspace]

members = [
  "crates/hc-utils",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[patch.crates-io]
hdk = {git = "https://github.com/holochain/holochain.git", rev = "12e990f06b381b29b98f2c6bc15623af928d5787", package = "hdk", version = "0.0.101-alpha.0"}
# paste = "1.0.5"
